spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topic:
      shipment-created: logistics.shipment.created
      shipment-status-updated: logistics.shipment.status.updated
      driver-assigned: logistics.driver.assigned
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: notification-service
    server: ${API_GATEWAY:http://localhost:4953}/notification
    title: Notification service
    version: 1.0.0
