spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:shipment_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      shipment-created: logistics.shipment.created
      status-updated: logistics.shipment.status.updated
      driver-assigned: logistics.driver.assigned

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
openapi:
  service:
    api-docs: shipment-service
    server: ${API_GATEWAY:http://localhost:4953}/shipment
    title: Shipment service
    version: 1.0.0
