spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:shipment_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

service:
  shipment:
    url: ${SHIPMENT_SERVICE_URL:http://shipment-service:8094}
  driver:
    url: ${DRIVER_SERVICE_URL:http://driver-service:8096}
  vehicle:
    url: ${VEHICLE_SERVICE_URL:http://vehicle-service:8097}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
openapi:
  service:
    api-docs: logistics-service
    server: ${API_GATEWAY:http://localhost:4953}/logistics
    title: Logistics Orchestrator service
    version: 1.0.0
